#include <string>

std::string poem =
    "Whispers of Time\n\n"
    "In the hush of dawn where the shadows play,\n"
    "The world awakens, shaking off the night,\n"
    "Soft whispers of the wind begin to sway,\n"
    "As sunbeams break, painting everything bright.\n\n"
    "A brook babbles softly, secrets it keeps,\n"
    "Winding through meadows where wildflowers bloom,\n"
    "A canvas of colors where silence seeps,\n"
    "In nature’s embrace, all worries find room.\n\n"
    "The trees stand tall, their branches outstretched,\n"
    "Guardians of stories from ages long past,\n"
    "Each ring in their trunk, a memory etched,\n"
    "Of storms they have weathered, of shadows they cast.\n\n"
    "Upon a small hill where the daisies sway,\n"
    "A child sits dreaming, lost in her thoughts,\n"
    "Her laughter, a melody that dances away,\n"
    "Like echoes of joy that time never rots.\n\n"
    "She watches the clouds as they drift and they curl,\n"
    "Imagining worlds where the magic is true,\n"
    "Where dragons can soar and the ocean can swirl,\n"
    "And wishes are granted, as dreams often do.\n\n"
    "But time is a thief, with a heart made of steel,\n"
    "It steals away moments, both precious and dear,\n"
    "Yet in every heartbeat, there’s something to feel,\n"
    "A pulse of existence, a rhythm to cheer.\n\n"
    "The seasons parade in their colorful dress,\n"
    "Spring whispers promise, as blossoms ignite,\n"
    "Summer, a blaze, with its warmth to possess,\n";
